// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $activities from "./routes/activities.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_post from "./routes/api/post.ts";
import * as $blogs from "./routes/blogs.tsx";
import * as $blogs_name_ from "./routes/blogs/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $post from "./routes/post.tsx";
import * as $Poster from "./islands/Poster.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/activities.tsx": $activities,
    "./routes/api/login.ts": $api_login,
    "./routes/api/post.ts": $api_post,
    "./routes/blogs.tsx": $blogs,
    "./routes/blogs/[name].tsx": $blogs_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/post.tsx": $post,
  },
  islands: {
    "./islands/Poster.tsx": $Poster,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
